import type { Video } from '@/lib/dashboard-types'

/** Apify 연동 전 TikTok 숏폼 레퍼런스 미리보기 (대시보드 UI 검증용) */
export const DUMMY_TIKTOK_CHANNELS = [
  { channel_id: 'tt-senior-money', channel_name: '@시니어재테크', followers: 128000, avg_views: 18500 },
  { channel_id: 'tt-finance-daily', channel_name: '@경제한줄', followers: 89000, avg_views: 12200 },
  { channel_id: 'tt-pension-tip', channel_name: '@연금이야기', followers: 210000, avg_views: 24000 },
] as const

export const DUMMY_TIKTOK_VIDEOS: Video[] = [
  {
    id: 9001,
    videoId: 'tt-dummy-001',
    tier: 'S',
    title: '2025 연금 개편, 지금 꼭 알아야 할 3가지 #시니어 #재테크',
    channel: '@시니어재테크',
    channelId: 'tt-senior-money',
    views: 284000,
    vsAvg: 5.2,
    platform: 'tiktok',
    publishedAt: '2026-05-17',
    keyword: '연금',
    duration: 58,
    format: 'short',
  },
  {
    id: 9002,
    videoId: 'tt-dummy-002',
    tier: 'A',
    title: '금리 동결인데 왜 예금이 위험해질까? 60초 정리',
    channel: '@경제한줄',
    channelId: 'tt-finance-daily',
    views: 156000,
    vsAvg: 3.8,
    platform: 'tiktok',
    publishedAt: '2026-05-16',
    keyword: '금리',
    duration: 62,
    format: 'short',
  },
  {
    id: 9003,
    videoId: 'tt-dummy-003',
    tier: 'A',
    title: '전세 사기 피하는 체크리스트 (부모님께 공유)',
    channel: '@연금이야기',
    channelId: 'tt-pension-tip',
    views: 412000,
    vsAvg: 4.1,
    platform: 'tiktok',
    publishedAt: '2026-05-15',
    keyword: '전세',
    duration: 45,
    format: 'short',
  },
  {
    id: 9004,
    videoId: 'tt-dummy-004',
    tier: 'B',
    title: '국민연금 수령액, 나이별로 이렇게 달라집니다',
    channel: '@시니어재테크',
    channelId: 'tt-senior-money',
    views: 98000,
    vsAvg: 2.4,
    platform: 'tiktok',
    publishedAt: '2026-05-14',
    keyword: '국민연금',
    duration: 72,
    format: 'short',
  },
  {
    id: 9005,
    videoId: 'tt-dummy-005',
    tier: 'S',
    title: '은퇴 후 월 200만원 버는 현실적인 방법 5가지',
    channel: '@경제한줄',
    channelId: 'tt-finance-daily',
    views: 520000,
    vsAvg: 6.3,
    platform: 'tiktok',
    publishedAt: '2026-05-12',
    keyword: '은퇴',
    duration: 89,
    format: 'short',
  },
  {
    id: 9006,
    videoId: 'tt-dummy-006',
    tier: 'B',
    title: '주식 말고 이것부터 하세요 (시니어 투자)',
    channel: '@연금이야기',
    channelId: 'tt-pension-tip',
    views: 73000,
    vsAvg: 1.9,
    platform: 'tiktok',
    publishedAt: '2026-05-10',
    keyword: '투자',
    duration: 54,
    format: 'short',
  },
]
